.PHONY : all linux mingw

all : linux

linux : 
	gcc -g -Wall --shared -o snapshot.so snapshot.c

mingw : 
	gcc -g -Wall --shared -o snapshot.dll snapshot.c -I/usr/local/include -L/usr/local/bin -llua52

mingw51 :
	gcc -g -Wall --shared -o snapshot.dll snapshot.c -I/usr/local/include -L/usr/local/bin -llua51
mac :
	gcc -c snapshot.c -I/usr/local/include;gcc -O2 -bundle -undefined dynamic_lookup -o snapshot.so snapshot.o
